package controller;

import dao.FeeDAO;
import dao.StudentDAO;
import model.Fee;
import model.Student;
import org.json.JSONObject;
import service.RazorpayService;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

/**
 * RazorpayOrderServlet - Creates server-side Razorpay orders for student fee checkout
 * URL Mapping: /create-razorpay-order
 */
public class RazorpayOrderServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    private RazorpayService razorpayService;
    private StudentDAO studentDAO;
    private FeeDAO feeDAO;

    @Override
    public void init() throws ServletException {
        this.razorpayService = new RazorpayService();
        this.studentDAO = new StudentDAO();
        this.feeDAO = new FeeDAO();
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        response.setContentType("application/json");
        response.setCharacterEncoding("UTF-8");
        PrintWriter out = response.getWriter();
        JSONObject jsonResp = new JSONObject();

        HttpSession session = request.getSession(false);
        if (session == null || !"student".equals(session.getAttribute("userRole"))) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            jsonResp.put("status", "error");
            jsonResp.put("message", "Authentication required. Please login as student.");
            out.print(jsonResp.toString());
            out.flush();
            return;
        }

        try {
            int studentId = (Integer) session.getAttribute("studentId");
            
            // Check if student has a generated fee
            Fee latestFee = feeDAO.getLatestFeeByStudentId(studentId);
            if (latestFee == null) {
                jsonResp.put("status", "error");
                jsonResp.put("message", "Fee has not been generated by admin yet. Online payment is unavailable.");
                out.print(jsonResp.toString());
                out.flush();
                return;
            }

            if (latestFee.getDueAmount() != null && latestFee.getDueAmount().compareTo(BigDecimal.ZERO) <= 0) {
                jsonResp.put("status", "error");
                jsonResp.put("message", "All fee dues have already been cleared.");
                out.print(jsonResp.toString());
                out.flush();
                return;
            }

            String amountStr = request.getParameter("amount");

            if (amountStr == null || amountStr.trim().isEmpty()) {
                jsonResp.put("status", "error");
                jsonResp.put("message", "Payment amount is required.");
                out.print(jsonResp.toString());
                out.flush();
                return;
            }

            double amount = Double.parseDouble(amountStr.trim());
            if (amount <= 0) {
                jsonResp.put("status", "error");
                jsonResp.put("message", "Amount must be greater than zero.");
                out.print(jsonResp.toString());
                out.flush();
                return;
            }

            // Cap at due amount
            if (latestFee.getDueAmount() != null && BigDecimal.valueOf(amount).compareTo(latestFee.getDueAmount()) > 0) {
                amount = latestFee.getDueAmount().doubleValue();
            }

            Student student = studentDAO.getStudentById(studentId);
            String studentName = (student != null) ? student.getName() : "Student #" + studentId;
            String studentEmail = (student != null && student.getEmail() != null) ? student.getEmail() : "";
            String studentMobile = (student != null && student.getMobile() != null) ? student.getMobile() : "";

            String receiptPrefix = "ORD-" + System.currentTimeMillis();
            Map<String, String> notes = new HashMap<>();
            notes.put("student_id", String.valueOf(studentId));
            notes.put("student_name", studentName);
            notes.put("course", (student != null && student.getCourse() != null) ? student.getCourse() : "");

            // Call Razorpay Orders API on server
            Map<String, Object> orderResult = razorpayService.createOrder(amount, receiptPrefix, notes);

            if ("SUCCESS".equals(orderResult.get("status"))) {
                jsonResp.put("status", "success");
                jsonResp.put("orderId", orderResult.get("orderId"));
                jsonResp.put("amount", amount);
                jsonResp.put("amountPaise", orderResult.get("amountPaise"));
                jsonResp.put("currency", orderResult.get("currency"));
                jsonResp.put("keyId", orderResult.get("keyId"));
                jsonResp.put("studentName", studentName);
                jsonResp.put("studentEmail", studentEmail);
                jsonResp.put("studentMobile", studentMobile);
            } else {
                jsonResp.put("status", "error");
                jsonResp.put("message", "Unable to create Razorpay order on server.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            jsonResp.put("status", "error");
            jsonResp.put("message", "Server error: " + e.getMessage());
        }

        out.print(jsonResp.toString());
        out.flush();
    }
}
