package service;

import dao.FeeDAO;
import dao.PaymentDAO;
import dao.StudentDAO;
import model.Fee;
import model.Payment;
import model.Student;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * PaymentService - Coordinates payment transactions, signature validation, and fee record updates in MongoDB
 */
public class PaymentService {

    private final RazorpayService razorpayService;
    private final PaymentDAO paymentDAO;
    private final FeeDAO feeDAO;
    private final StudentDAO studentDAO;

    public PaymentService() {
        this.razorpayService = new RazorpayService();
        this.paymentDAO = new PaymentDAO();
        this.feeDAO = new FeeDAO();
        this.studentDAO = new StudentDAO();
    }

    /**
     * Process and finalize a student fee payment after Razorpay checkout
     */
    public Map<String, Object> processRazorpayPayment(int studentId, BigDecimal amount, String razorpayOrderId, 
                                                       String razorpayPaymentId, String razorpaySignature, String paymentMethod) {
        Map<String, Object> result = new HashMap<>();

        // 1. Validation of parameters
        if (studentId <= 0 || amount == null || amount.compareTo(BigDecimal.ZERO) <= 0 ||
            razorpayPaymentId == null || razorpayPaymentId.trim().isEmpty()) {
            result.put("success", false);
            result.put("message", "Invalid payment parameters provided.");
            return result;
        }

        // 2. Check if fee record exists for this student
        Fee latestFee = feeDAO.getLatestFeeByStudentId(studentId);
        if (latestFee == null) {
            result.put("success", false);
            result.put("message", "Fee has not been generated by hostel administration yet. Cannot accept payments.");
            return result;
        }

        if (latestFee.getDueAmount() != null && latestFee.getDueAmount().compareTo(BigDecimal.ZERO) <= 0) {
            result.put("success", false);
            result.put("message", "All fee dues have already been cleared for your account.");
            return result;
        }

        // 3. Prevent duplicate payment processing
        if (paymentDAO.isPaymentIdProcessed(razorpayPaymentId)) {
            result.put("success", false);
            result.put("message", "This transaction has already been recorded and processed.");
            return result;
        }

        // 4. Cryptographic Signature Verification
        boolean signatureValid = razorpayService.verifyPaymentSignature(razorpayOrderId, razorpayPaymentId, razorpaySignature);
        if (!signatureValid) {
            System.err.println("[PaymentService] Signature verification failed for Order: " + razorpayOrderId + ", Payment: " + razorpayPaymentId);
            Payment failedPayment = new Payment();
            failedPayment.setStudentId(studentId);
            failedPayment.setRazorpayOrderId(razorpayOrderId);
            failedPayment.setRazorpayPaymentId(razorpayPaymentId);
            failedPayment.setAmount(amount);
            failedPayment.setPaymentStatus("FAILED_SIGNATURE_MISMATCH");
            failedPayment.setSignatureVerificationStatus(false);
            failedPayment.setPaymentMethod(paymentMethod != null ? paymentMethod : "Razorpay Online");
            paymentDAO.savePayment(failedPayment);

            result.put("success", false);
            result.put("message", "Payment verification failed. Cryptographic signature does not match.");
            return result;
        }

        // 5. Fetch student details for audit
        Student student = studentDAO.getStudentById(studentId);
        String studentName = (student != null) ? student.getName() : "Student #" + studentId;

        // 6. Update Fee Record in MongoDB
        String receiptNumber = feeDAO.recordOnlinePayment(studentId, amount, razorpayPaymentId.trim(), razorpayOrderId, paymentMethod);

        if (receiptNumber == null) {
            result.put("success", false);
            result.put("message", "Payment was verified but failed to update fee records in database.");
            return result;
        }

        // 7. Record verified Payment Log in MongoDB payments collection
        Payment successPayment = new Payment();
        successPayment.setStudentId(studentId);
        successPayment.setStudentName(studentName);
        successPayment.setRazorpayOrderId(razorpayOrderId);
        successPayment.setRazorpayPaymentId(razorpayPaymentId);
        successPayment.setAmount(amount);
        successPayment.setCurrency("INR");
        successPayment.setPaymentStatus("SUCCESS");
        successPayment.setPaymentDate(new Date());
        successPayment.setPaymentMethod(paymentMethod != null ? paymentMethod : "Razorpay Online (UPI/Card)");
        successPayment.setSignatureVerificationStatus(true);
        successPayment.setReceiptNumber(receiptNumber);
        paymentDAO.savePayment(successPayment);

        result.put("success", true);
        result.put("receiptNumber", receiptNumber);
        result.put("paymentId", successPayment.getPaymentId());
        result.put("razorpayPaymentId", razorpayPaymentId);
        result.put("amount", amount);
        result.put("message", "Payment verified and recorded successfully!");
        return result;
    }
}
